# Copyright (C) 2021 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker compose up
#           docker compose down

# docker compose exec mysql bash
# mysql --user=root --password=p

---
# https://docs.docker.com/compose/compose-file
# https://docs.docker.com/compose/compose-file/compose-file-v3
services:
  mysql:
    image: mysql:8.0.32-oracle
    ports:
      - published: 3306
        target: 3306
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/mysql/db
        # /etc/mysql/my.cnf
        # SELECT @@datadir;
        target: /var/lib/mysql
      - type: bind
        source: C:/Zimmermann/volumes/mysql/mysqld
        target: /var/run/mysqld
      - type: bind
        source: C:/Zimmermann/volumes/mysql/run-mysqld
        target: /run/mysqld
      - type: bind
        source: C:/Zimmermann/volumes/mysql/log
        target: /var/log
      - type: bind
        source: C:/Zimmermann/volumes/mysql/tmp
        target: /tmp
      - type: bind
        source: C:/Zimmermann/volumes/mysql/sql
        target: /sql
        read_only: true
      # ggf. log_bin=OFF setzen
      #- type: bind
      #  source: C:/Zimmermann/volumes/mysql/my.cnf
      #  target: /etc/my.cnf
    env_file: [mysql.env]
#    user: "mysql:mysql"
    # docker inspect mysql --format '{{ .Id }}: SecurityOpt={{ .HostConfig.SecurityOpt }}'
    security_opt:
      - label:user:mysql
      - no-new-privileges:true
    container_name: mysql
    # gleicher Name wie der Kubernetes-Service
    hostname: mysql
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2048M
    healthcheck:
      test: [CMD, mysqladmin, --user=root, --password=p, --host=mysql, ping]
      interval: 5s
      timeout: 2s
      start_period: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    links: [mysql]
    ports:
      - published: 8889
        target: 80
    env_file: [mysql.env]
    # kein dedizierter User im Image vorhanden
    container_name: phpmyadmin
    # https://github.com/phpmyadmin/docker/issues/293
    hostname: phpmyadmin.mysql.docker
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 768M

# dbeaver/cloudbeaver hat 5 Mio Downloads bei https://hub.docker.com.
# https://cloudbeaver.io https://github.com/dbeaver/cloudbeaver
# als User "cbadmin" muss man einen "normalen" User einrichten
# UUIDs werden binaer angezeigt
#  dbeaver:
#    image: dbeaver/cloudbeaver:22.3.3
#    links: [mysql]
#    ports:
#      - published: 8978
#        target: 8978
#    volumes:
#      - type: bind
#        source: C:/Zimmermann/volumes/mysql/dbeaver-workspace
#        target: /opt/cloudbeaver/workspace
#    env_file: [dbeaver.env]
#    environment:
#      TZ: Europe/Berlin
#    container_name: dbeaver
#    hostname: dbeaver
#    deploy:
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: 768M

# adminer hat ueber 100 Mio Downloads und ist ein einfaches PHP-Skript.
# Letztes Release ist von Mai 2021 https://github.com/vrana/adminer https://www.adminer.org
#  adminer:
#    image: adminer:4.8.1-standalone
#    links: [mysql]
#    ports:
#      - published: 8889
#        target: 8080
#    environment:
#      ADMINER_DEFAULT_SERVER: mysql
#      TZ: Europe/Berlin
#    #user: "adminer:adminer"
#    container_name: adminer
#    hostname: adminer
#    deploy:
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: 768M

# !!! GUI ist SEHR instabil bei Windows
#  workbench:
#    image: linuxserver/mysql-workbench:8.0.32
#    links: [mysql]
#    ports:
#      - published: 8889
#        target: 3000
#    volumes:
#      - type: bind
#        source: C:/Zimmermann/volumes/mysql/workbench-config
#        target: /config
#    env_file: [mysql-workbench.env]
#    #user: 1000:1000
#    cap_add: [IPC_LOCK]
#    restart: unless-stopped
#    container_name: workbench
#    hostname: workbench
#    deploy:
#      resources:
#        limits:
#          cpus: "1"
#          memory: 768M
